resources:
- repo: self
  fetchDepth: 1
pool:
  vmImage: ubuntu-20.04
trigger:
- master
variables:
  TargetFramework: 'net6.0'
  BuildConfiguration: 'Release' #PROJECT-ID/REPO/IMAGE
  DockerImageName: 'int-poc-app-compliance/egpt-rlef/clouddemo'
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CmdLine@1
  displayName: 'Lock image version in deployment.yaml'
  inputs:
    filename: /bin/bash
    arguments: '-c "awk ''{gsub(\"CLOUDDEMO_IMAGE\", \"us-central1-docker.pkg.dev/$(DockerImageName):$(Build.BuildId)\", $0); print}'' deployement.yaml > $(build.artifactstagingdirectory)/deployement.yaml"'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
- task: Docker@2
  displayName: 'Login to Container Registry'
  inputs:
    command: login
    containerRegistry: 'GCR connection'
- task: Docker@2
  displayName: 'Build and push image'
  inputs:
    Dockerfile: '**/AzureDockerfile'
    command: buildAndPush
    repository: '$(DockerImageName)'

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'Kubernetes'
    namespace: 'default'
    manifests: 'deployement.yaml'